# Generated by Django 3.0.6 on 2020-08-25 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_on', to='auctions.AuctionListings'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commented_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commented_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_on', to='auctions.AuctionListings'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='added_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_item', to='auctions.AuctionListings'),
        ),
    ]
