# Generated by Django 3.0.6 on 2020-09-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200825_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='bid_active',
            field=models.BooleanField(default=True),
        ),
    ]
